version: 2
jobs:
  
  build:
    machine: true
    steps:
      - run: echo Build Finish
  
  deploy:
    machine: true
    steps:
      - run: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      - run: sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update
      - run: gcloud auth activate-service-account $ACCOUNT --key-file ${HOME}/gcloud-service-key.json
      - run: ssh tai_akihiko_private@www.darth-vader.tokyo -C /var/www/html/www.darth-vader.tokyo/deploy.sh
      - run: echo Deploy Finish

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - deploy
